# Generated by Django 5.0.6 on 2024-06-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('department', models.CharField(max_length=50)),
                ('working', models.BooleanField(default=True)),
            ],
        ),
    ]
