# Generated by Django 5.0.6 on 2024-06-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='address',
            field=models.CharField(default='adarsul', max_length=200),
        ),
    ]
